// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwk1C_grpKkPQegmzGy7Wd9o4AI_vUBmE',
    appId: '1:829104373886:web:89f4ef669a8a37b039d82f',
    messagingSenderId: '829104373886',
    projectId: 'instagram-clone-ae003',
    authDomain: 'instagram-clone-ae003.firebaseapp.com',
    storageBucket: 'instagram-clone-ae003.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMZYRNTEevCJxh5F3rAUITLKHPSLXLynk',
    appId: '1:829104373886:android:fb8ffca112e7b95739d82f',
    messagingSenderId: '829104373886',
    projectId: 'instagram-clone-ae003',
    storageBucket: 'instagram-clone-ae003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTJOUw7JWd7odgQ8msWFKgbfJ8-VJZBe0',
    appId: '1:829104373886:ios:5c1379b9c27fd31739d82f',
    messagingSenderId: '829104373886',
    projectId: 'instagram-clone-ae003',
    storageBucket: 'instagram-clone-ae003.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTJOUw7JWd7odgQ8msWFKgbfJ8-VJZBe0',
    appId: '1:829104373886:ios:5a4d37ec94657e9439d82f',
    messagingSenderId: '829104373886',
    projectId: 'instagram-clone-ae003',
    storageBucket: 'instagram-clone-ae003.appspot.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
